# Generated by Django 5.0.6 on 2024-08-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_description',
            new_name='description',
        ),
    ]
